services:
  db:
    image: postgres:latest
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - database.env
    ports:
      - "5432:5432"
  app:
    container_name: dotnet5
    build: ./server
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8000:80"
    links:
      - "db:db"
    depends_on:
      - db